### ISSUE TITLE
node 0.4.2: TypeError: Cannot read property 'Set-Cookie' of undefined

### ISSUE THREAD

**Issue by diversario** [Marak/session.js#2]
I get this when using session.magicSession() with node-static server:
    /usr/local/lib/node/.npm/response/0.1.0/package/lib/response.js:14
            headers[k] = headers[k] || that._additionalHeaders[k];
                                ^
    TypeError: Cannot read property 'Set-Cookie' of undefined
    at /usr/local/lib/node/.npm/response/0.1.0/package/lib/response.js:14:33
    at Array.forEach (native)
    at ServerResponse.writeHead (/usr/local/lib/node/.npm/response/0.1.0/package/lib/response.js:13:46)
    at ServerResponse._implicitHeader (http.js:765:8)
    at ServerResponse.end (http.js:629:10)
    at /home/user/node/api.js:19:13
    at /home/user/node/db.js:98:3
    at IncomingMessage.<anonymous> (/usr/local/lib/node/.npm/couch-client/0.0.4/package/lib/couch-client.js:80:25)
    at IncomingMessage.emit (events.js:59:20)
    at HTTPParser.onMessageComplete (http.js:111:23)

api.js:19:
    response.end(result);

My .js with server code passes request and response down to other modules and node throws this from one of them.

Session does work in the server code module.

**Comment by Marak** [comment]
Hrmm, I had responded to this earlier but it appears the post didn't go through.

I think magicSession stuff isn't going to work with node-static without some modifications. I'd recommend using the regular middle-ware api. 

It's possible that magicSession will work if you require the session module after you create your node-static server...

**Comment by diversario** [comment]
Yeah, there were no messages before this one.

As for middleware, all I could find is middleware for Connect and express, which I'm not sure - will it work outside of those? Like session in Connect - it seems great but it requires connect and connect, as far as I can tell, must be used to create a server, which I create with node-static. So, I'm confused. I'm new to node and I haven't figured out some things yet.

**Comment by Marak** [comment]
Hrmm? The middle-ware api for session.js is in the documentation. Just modify the request and response objects in a callback of your server. 

```
    Using session.js as a middle-ware
      var http = require('http'), 
          session = require('./lib/core').session;

      // let's create a basic http server!
      http.createServer(function (request, response) {

        // before we process any part of the request, let's use the session middle-ware!
        session(request, response, function(request, response){

          // now we can access request.session

          // after the session middleware has executed, let's finish processing the request
          response.writeHead(200, {'Content-Type': 'text/plain'});
          response.write('request.session: \n' + JSON.stringify(request.session, 2, true));
          response.end();

        });

      }).listen(8080);

      /* server started */  
      console.log('> hello world running on port 8080');
```

Try reading http://blog.nodejitsu.com/sessions-and-cookies-in-node too.

You can also try using Connect + the connect static and session modules.
